title: How I Made $5000 in the Stock Market

collections:
  posts:
    output: true
    permalink: /posts/:slug

baseurl: /

sass: 
  style: compressed

defaults:
  - scope:
      path: "_assets/img/pulse"
    values:
      market_pulse: true

### exclude the instructions / write-up in the README.md
exclude:
- README.md

tag_page: '/tags'

highlighter: rouge
markdown: kramdown

#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []
