title: How I Made $5000 in the Stock Market
timezone: America/New_York
future: true

collections:
  posts:
    output: true
    permalink: /posts/:slug
  columns:
    output: true

baseurl: 

sass: 
  style: compressed

defaults:
  - scope:
      path: "assets/img/pulse"
    values:
      market_pulse: true
  - scope:
      path: "_columns/The_Big_Picture"
    values:
      the_big_picture: true
      permalink: /columns/the-big-picture/:name
  - scope:
      path: "_columns/Stock_Of_the_Day"
    values:
      stock_of_the_day: true
      permalink: /columns/stock-of-the-day/:name
  - scope:
      path: "_columns/Swing_Trading"
    values:
      swing_trading: true
      permalink: /columns/swing-trading/:name
  - scope:
      path: "_columns/Investors_Corner"
    values:
      investors_corner: true
      permalink: /columns/investors-corner/:name
  - scope:
      path: "_columns/Stock_Analysis"
    values:
      stock_analysis: true
      permalink: /columns/stock-analysis/:name
  - scope:
      path: "_columns/Barrons_Weekly"
    values:
      barrons_weekly: true
      permalink: /columns/barrons-weekly/:name

### exclude the instructions / write-up in the README.md
exclude:
- README.md

tag_page: '/tags'

highlighter: rouge
markdown: kramdown

#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []
